#!/usr/bin/env python3
"""Build the self-contained Verilog file used by custom_gds.

The Tiny Tapeout custom_gds action copies one Verilog file into the
submission artifact.  This project keeps the real RTL split across src/ with
`include directives, so this script expands the local project sources into one
file while preserving the normal source files for simulation, FPGA, and local
TT builds.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

INCLUDE_RE = re.compile(r'^\s*`include\s+"[^"]+"\s*$')

SOURCE_ORDER = [
    "target_pdk.v",
    "project_config.v",
    "JTAG/jtag_core.v",
    "SPI/spi_slave.v",
    "UART/uart_rx_min.v",
    "UART/uart_tx_min.v",
    "UART/uart_trng_ascii_core.v",
    "TRNG/trng_cfg_ascii_core.v",
    "PINS/pin_id_core.v",
    "ANALOG/analog_experiment_stub.v",
    "TRNG/trng_lab_core.v",
    "TRNG/trng_stub.v",
    "tt_um_main.v",
    "project.v",
]


def strip_local_includes(text: str) -> str:
    lines: list[str] = []
    for line in text.splitlines():
        if INCLUDE_RE.match(line):
            lines.append("/* local include expanded by tools/build_custom_gds_verilog.py */")
        else:
            lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", default="src", help="Source directory")
    parser.add_argument("--out", required=True, help="Output Verilog file")
    args = parser.parse_args()

    src_dir = Path(args.src)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    parts: list[str] = []
    parts.append("/*\n")
    parts.append(" * Generated by tools/build_custom_gds_verilog.py.\n")
    parts.append(" * Do not edit this file by hand.  Edit the source files under src/.\n")
    parts.append(" */\n\n")

    for rel in SOURCE_ORDER:
        path = src_dir / rel
        if not path.is_file():
            raise FileNotFoundError(path)
        parts.append("\n/* ---- begin expanded source: src/%s ---- */\n" % rel)
        parts.append(strip_local_includes(path.read_text()))
        parts.append("/* ---- end expanded source: src/%s ---- */\n" % rel)

    out_path.write_text("".join(parts))

    generated = out_path.read_text()
    remaining_includes = [line for line in generated.splitlines() if INCLUDE_RE.match(line)]
    if remaining_includes:
        raise RuntimeError("Generated file still contains active `include directives")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
